// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Monitor struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Url            string
	IntervalSecond int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
