// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (id, user_id, name, url, interval_second)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, url, interval_second, created_at, updated_at
`

type CreateMonitorParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Url            string
	IntervalSecond int32
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.IntervalSecond,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecond,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMonitor, id)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, name, url, interval_second, created_at, updated_at FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecond,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, url, interval_second, created_at, updated_at FROM monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID uuid.UUID) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecond,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $2,
    url = $3,
    interval_second = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, url, interval_second, created_at, updated_at
`

type UpdateMonitorParams struct {
	ID             uuid.UUID
	Name           string
	Url            string
	IntervalSecond int32
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.IntervalSecond,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecond,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
