// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Name      string
	Url       string
	Type      string
	IsActive  *bool
	Settings  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MonitorGroup struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	IsActive  *bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Notification struct {
	ID         uuid.UUID
	RunnerID   uuid.UUID
	NotifierID int32
	Type       string
	Trigger    string
	Message    string
	IsActive   *bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Notifier struct {
	ID          int32
	Type        string
	DisplayName string
}

type Runner struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	MonitorID      uuid.UUID
	Name           string
	Region         string
	IntervalSecond int32
	IsActive       *bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RunnerHistory struct {
	ID             uuid.UUID
	RunnerID       uuid.UUID
	Status         string
	Message        *string
	StartedAt      pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	DurationMs     *int32
	ResponseTimeMs *int32
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
