// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Monitor struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Name      string          `json:"name"`
	Url       string          `json:"url"`
	Type      string          `json:"type"`
	Settings  json.RawMessage `json:"settings"`
	IsEnabled bool            `json:"is_enabled"`
	CreatedAt *time.Time      `json:"created_at"`
	UpdatedAt *time.Time      `json:"updated_at"`
}

type Notification struct {
	ID         uuid.UUID  `json:"id"`
	RunnerID   uuid.UUID  `json:"runner_id"`
	NotifierID int32      `json:"notifier_id"`
	Type       string     `json:"type"`
	Trigger    string     `json:"trigger"`
	Message    string     `json:"message"`
	IsEnabled  bool       `json:"is_enabled"`
	CreatedAt  *time.Time `json:"created_at"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

type Notifier struct {
	ID          int32  `json:"id"`
	Type        string `json:"type"`
	DisplayName string `json:"display_name"`
}

type Runner struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	MonitorID      uuid.UUID  `json:"monitor_id"`
	Name           string     `json:"name"`
	Region         string     `json:"region"`
	IntervalSecond int32      `json:"interval_second"`
	IsEnabled      bool       `json:"is_enabled"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

type RunnerHistory struct {
	ID             uuid.UUID  `json:"id"`
	RunnerID       uuid.UUID  `json:"runner_id"`
	Status         string     `json:"status"`
	Message        *string    `json:"message"`
	StartedAt      *time.Time `json:"started_at"`
	EndedAt        *time.Time `json:"ended_at"`
	ResponseTimeMs *int32     `json:"response_time_ms"`
	CreatedAt      *time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}
