// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    id, user_id, name, url, type, settings, is_enabled
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, url, type, settings, is_enabled, created_at, updated_at
`

type CreateMonitorParams struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Name      string          `json:"name"`
	Url       string          `json:"url"`
	Type      string          `json:"type"`
	Settings  json.RawMessage `json:"settings"`
	IsEnabled bool            `json:"is_enabled"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.Settings,
		arg.IsEnabled,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Settings,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const findAllMonitors = `-- name: FindAllMonitors :many
SELECT id, user_id, name, url, type, settings, is_enabled, created_at, updated_at 
FROM monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) FindAllMonitors(ctx context.Context, userID uuid.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, findAllMonitors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.Settings,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMonitorByID = `-- name: FindMonitorByID :one
SELECT id, user_id, name, url, type, settings, is_enabled, created_at, updated_at 
FROM monitors
WHERE id = $1
`

func (q *Queries) FindMonitorByID(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, findMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Settings,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET 
    name = $2,
    url = $3,
    type = $4,
    settings = $5,
    is_enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, url, type, settings, is_enabled, created_at, updated_at
`

type UpdateMonitorParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Url       string          `json:"url"`
	Type      string          `json:"type"`
	Settings  json.RawMessage `json:"settings"`
	IsEnabled bool            `json:"is_enabled"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.Settings,
		arg.IsEnabled,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Settings,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitorIsEnabled = `-- name: UpdateMonitorIsEnabled :one
UPDATE monitors
SET 
  is_enabled = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, url, type, settings, is_enabled, created_at, updated_at
`

type UpdateMonitorIsEnabledParams struct {
	ID        uuid.UUID `json:"id"`
	IsEnabled bool      `json:"is_enabled"`
}

func (q *Queries) UpdateMonitorIsEnabled(ctx context.Context, arg UpdateMonitorIsEnabledParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitorIsEnabled, arg.ID, arg.IsEnabled)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Settings,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
