// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runner_history.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findHistoryByRunnerID = `-- name: FindHistoryByRunnerID :many
SELECT
    id,
    runner_id,
    status,
    message,
    started_at,
    ended_at,
    duration_ms,
    response_time_ms,
    created_at
FROM runner_histories
WHERE runner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) FindHistoryByRunnerID(ctx context.Context, runnerID uuid.UUID) ([]RunnerHistory, error) {
	rows, err := q.db.Query(ctx, findHistoryByRunnerID, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunnerHistory
	for rows.Next() {
		var i RunnerHistory
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.Status,
			&i.Message,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRunnerHistory = `-- name: SaveRunnerHistory :exec
INSERT INTO runner_histories (
    id,
    runner_id,
    status,
    message,
    started_at,
    ended_at,
    duration_ms,
    response_time_ms,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
`

type SaveRunnerHistoryParams struct {
	ID             uuid.UUID  `json:"id"`
	RunnerID       uuid.UUID  `json:"runner_id"`
	Status         string     `json:"status"`
	Message        *string    `json:"message"`
	StartedAt      *time.Time `json:"started_at"`
	EndedAt        *time.Time `json:"ended_at"`
	DurationMs     *int32     `json:"duration_ms"`
	ResponseTimeMs *int32     `json:"response_time_ms"`
}

func (q *Queries) SaveRunnerHistory(ctx context.Context, arg SaveRunnerHistoryParams) error {
	_, err := q.db.Exec(ctx, saveRunnerHistory,
		arg.ID,
		arg.RunnerID,
		arg.Status,
		arg.Message,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMs,
		arg.ResponseTimeMs,
	)
	return err
}
